//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace E_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresses
    {
        public Adresses()
        {
            this.Membres = new HashSet<Membres>();
        }
    
        [Display (Name = "Adresse")]
        public int Id_adresse { get; set; }
        [Display(Name="Numéro")]
        public string num_civique { get; set; }
        [Display(Name="Nom de la rue")]
        public string rue { get; set; }
        [Display(Name="App. #")]
        public string app { get; set; }
        [Display(Name="Ville")]
        public string ville { get; set; }
        [Display(Name="Code postal")]
        public string code_postal { get; set; }
        [Display(Name="Province")]
        public string province { get; set; }

        [Display(Name = "Adresse complète")]
        public string AdresseComplete
        {
            get
            {
                return (this.num_civique + " " + this.rue + " " + this.app + ", " + this.ville + " " + this.province + " " + this.code_postal);
            }
        }
    
        public virtual ICollection<Membres> Membres { get; set; }
    }
}
