//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBiblioEntities : DbContext
    {
        public dbBiblioEntities()
            : base("name=dbBiblioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresses> Adresses { get; set; }
        public virtual DbSet<Emprunts> Emprunts { get; set; }
        public virtual DbSet<Livres> Livres { get; set; }
        public virtual DbSet<Membres> Membres { get; set; }

        public class ComplexView
        {
            public string titre { get; set; }
            public DateTime date_retour { get; set; }
            public DateTime date_emprunt { get; set; }

        }
    }
}
