//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace E_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprunts
    {
        [Display(Name = "No. d'emprunt")]
        public int Id_emprunt { get; set; }
        [Display(Name = "Date d'emprunt")]
        public System.DateTime date_emprunt { get; set; }
        [Display(Name = "Statut")]
        public string statut { get; set; }
        [Display(Name = "Identité du membre")]
        public int Id_membre { get; set; }
        [Display(Name = "Titre du livre")]
        public int Id_Livre { get; set; }
        [Display(Name = "Date de retour")]
        public Nullable<System.DateTime> date_retour { get; set; }
    
        public virtual Livres Livres { get; set; }
        public virtual Membres Membres { get; set; }
    }
}
