//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace E_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livres
    {
        public Livres()
        {
            this.Emprunts = new HashSet<Emprunts>();
        }
    
        [Display(Name = "No. du livre")]
        public int Id_Livre { get; set; }
        [Display(Name = "Titre du livre")]
        public string titre { get; set; }
        [Display(Name = "Nom de l'auteur")]
        public string auteur { get; set; }
        [Display(Name = "Nom de l'éditeur")]
        public string editeur { get; set; }
        [Display(Name = "Exemplaire")]
        public int exemplaires { get; set; }
        [Display(Name = "Catégorie")]
        public string categorie { get; set; }
    
        public virtual ICollection<Emprunts> Emprunts { get; set; }
    }
}
