//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace E_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membres
    {
        public Membres()
        {
            this.Emprunts = new HashSet<Emprunts>();
        }
    
        [Display(Name="ID du membre")]
        public int Id_membre { get; set; }
        [Display(Name="Nom de famille")]
        public string nom { get; set; }
        [Display(Name="Prénom")]
        public string prenom { get; set; }
        [Display(Name="Date de naissance")]
        public System.DateTime date_naissance { get; set; }
        [Display(Name="Sexe")]
        public string sexe { get; set; }
        [Display(Name="Téléphone")]
        public string tel { get; set; }
        [Display(Name="Courriel")]
        public string courriel { get; set; }
        [Display(Name = "NIP")]
        public string code { get; set; }
        [Display(Name = "Adresse")]
        public int Id_adresse { get; set; }

        [Display(Name = "Identité du membre")]
        public string IdentiteMembre
        {
            get
            {
                return (this.prenom + " " + this.prenom + " (" + this.code + ")");
            }
        }
    
        public virtual Adresses Adresses { get; set; }
        public virtual ICollection<Emprunts> Emprunts { get; set; }
    }
}
